apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kiali-ingress
  labels:
    app: kiali
spec:
  ingressClassName: traefik
  rules:
  - host: "kiali.istio-system.cloud.43.203.62.69.nip.io"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kiali
            port:
              number: 20001
